---
version: "3.9"
services:
  chatbot:
    container_name: chatbot
    build:
      context: ./chatbot/
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY}
    restart: unless-stopped
    networks:
      - discobot
    depends_on:
      - postgredb
    # Allows completing spotify OAuth process via terminal:
    stdin_open: true
    tty: true
    command: sh -c "/wait-for ${POSTGRES_HOSTNAME}:${POSTGRES_PORT} && python -u ./chatbot/chatbot.py"

  postgredb:
    image: postgres
    hostname: ${POSTGRES_HOSTNAME}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./debug_volumes/postgre_db/:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - discobot

  # Disable adminer for production
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - discobot

  # ==== BACKEND ====
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOSTNAME=${MONGO_HOSTNAME}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - discobot

networks:
  discobot: