# Generated by Django 3.1.6 on 2021-02-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_update_cron_expr', models.CharField(max_length=255)),
                ('testing_cron_expr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('spotify_auth_token', models.BinaryField(null=True)),
                ('encrypted_fernet_key', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('all_time_playlist_uri', models.CharField(max_length=255)),
                ('recent_playlist_uri', models.CharField(max_length=255)),
                ('buffer_playlist_uri', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discobot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monitor', models.BooleanField()),
                ('notify', models.BooleanField()),
                ('test', models.BooleanField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discobot.guild')),
            ],
        ),
    ]
