# Generated by Django 3.1.7 on 2021-04-05 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_update_cron_expr', models.CharField(max_length=255)),
                ('testing_cron_expr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('spotify_auth_token', models.BinaryField(null=True)),
                ('encrypted_fernet_key', models.BinaryField(null=True)),
                ('spotify_state', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('all_time_playlist_uri', models.CharField(max_length=255)),
                ('recent_playlist_uri', models.CharField(max_length=255)),
                ('buffer_playlist_uri', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discobot.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monitor', models.BooleanField()),
                ('notify', models.BooleanField()),
                ('test', models.BooleanField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discobot.guild')),
            ],
        ),
    ]
