# Generated by Django 3.1.7 on 2021-04-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discobot', '0004_auto_20210402_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotify_state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
